# Generated by Django 5.2.7 on 2025-11-10 13:32

import django.db.models.deletion
import payme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=payme.models.generateAccountNumber, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNSPECIFIED')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
