# Generated by Django 5.2.7 on 2025-11-12 10:52

import django.db.models.deletion
import payme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0002_alter_client_account_number_alter_client_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('receiver_account_number', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('deposit', 'Deposit')], default='transfer', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(default=payme.models.generateTRansactionId, max_length=40, unique=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payme.client')),
            ],
        ),
    ]
